// Auto-generated by LibreLane
module ALU(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[31:0] A,
  input[31:0] B,
  input[3:0] control,
  output[31:0] result,
  output zero
);
endmodule
