// Auto-generated by LibreLane
module registerfile(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input we,
  input rst,
  input[4:0] rs1,
  input[4:0] rs2,
  input[4:0] rd,
  input[31:0] wd,
  output[31:0] rd1,
  output[31:0] rd2
);
endmodule
